# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/langchain-tests',
                'doc_host': 'https://francescogianferraripini.github.io',
                'git_url': 'https://github.com/francescogianferraripini/langchain-tests',
                'lib_path': 'langchain_tests'},
  'syms': {'langchain_tests.core': {'langchain_tests.core.foo': ('core.html#foo', 'langchain_tests/core.py')}}}
